[package]
name = "loc"
version = "0.1.0"
edition = "2021"
description = "Command runner for the current working directory"

[dependencies]
anyhow = "1.0.87"
clap = { version = "4.5.17", features = ["derive"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
xdg = "2.5.2"
