[package]
name = "loc"
version = "0.1.0"
edition = "2021"
description = "Command runner for the current working directory"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
serde = { version = "1.0.204", features = ["derive"] }
