name: Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cross-compile: false

          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            cross-compile: false

          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            cross-compile: true

          - os: macos-latest
            target: x86_64-apple-darwin
            cross-compile: false

          - os: macos-latest
            target: aarch64-apple-darwin
            cross-compile: false

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v2

      - name: Install Cross
        if: ${{ matrix.cross-compile }}
        run: cargo install cross --git https://github.com/cross-rs/cross

      - run: cargo fmt --check --all

      - run: cargo clippy --no-deps --all-features
        env:
          RUSTFLAGS: -Dwarnings

      - run: ${{ matrix.cross-compile && 'cross' || 'cargo' }} build --target ${{ matrix.target }}
